# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

stages:
  - stage: 'BuildSatge'
    displayName: 'Build Satge'
    jobs:
      - job: 'Build'
        pool: 
          name: Default
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Restore the project'
            inputs:
              command: 'restore'
              projects: '**/*.csproj'
          
          - task: DotNetCoreCLI@2
            displayName: 'Build the project'
            inputs:
              command: 'build'
              arguments: '--configuration Release'
              projects: '**/*.csproj'
          
          - task: DotNetCoreCLI@2
            displayName: 'Publish the project'
            inputs:
              command: 'publish'
              projects: '**/*.csproj'
              publishWebProjects: false
              arguments: '--no-build --configuration Release --output $(Build.ArtifactStagingDirectory)/Release'
              zipAfterPublish: true
          
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: test
      - deployment: 'Deploy'
        displayName: 'Deploy'
        environment: 'Default'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: 'current'
                    artifactName: test
                    downloadPath: '$(System.ArtifactsDirectory)'
                - task: IISWebAppManagementOnMachineGroup@0
                  inputs:
                    EnableIIS: true
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'CreateOrUpdateWebsite'
                    WebsiteName: 'DevOpsAndGithubIntegration'
                    WebsitePhysicalPath: '%SystemDrive%\temp\DevOpsAndGithubIntegration'
                    WebsitePhysicalPathAuth: 'WebsiteWindowsAuth'
                    WebsiteAuthUserName: '$(iisUser)'
                    WebsiteAuthUserPassword: '$(iisPassword)'
                    AddBinding: true
                    Bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"7001","hostname":"","sslThumbprint":"","sniFlag":false}]}'
                    CreateOrUpdateAppPoolForWebsite: true
                    AppPoolNameForWebsite: 'DevOpsAndGithubIntegration'
                    DotNetVersionForWebsite: 'No Managed Code'
                    PipeLineModeForWebsite: 'Integrated'
                    AppPoolIdentityForWebsite: 'SpecificUser'
                    AppPoolUsernameForWebsite: '$(iisUser)'
                    AppPoolPasswordForWebsite: '$(iisPassword)'
                - task: IISWebAppDeploymentOnMachineGroup@0
                  inputs:
                    WebSiteName: 'DevOpsAndGithubIntegration'
                    VirtualApplication: '\'
                    Package: '$(System.ArtifactsDirectory)\**\*.zip'
                    
