trigger:
- '*'

stages:
  - stage: 'BuildSatge'
    displayName: 'Build Satge'
    jobs:
      - job: 'Build'
        pool: 
          name: Default
        variables:
          - name: branchNameToTileCase
            value: 'wwwww'
        steps:
          - task: InstallNetCoreRuntimeAndHosting@1
            inputs:
              version: '5.0'
              useProxy: false
              norestart: true
              iisReset: true
          - script: |
              echo ${{ variables.one }} # outputs initialValue
              echo $(one)
              echo ${{ variables.branchNameToTileCase }} # outputs initialValue
              echo $(branchNameToTileCase)
            displayName: First variable pass
          - powershell: Write-Host '##vso[task.setvariable variable=branchNameToTileCase]secondValue'
            displayName: Set new variable value
          - script: |
              echo ${{ variables.one }} # outputs initialValue
              echo $(one) # outputs secondValue
              echo ${{ variables.branchNameToTileCase }} # outputs initialValue
              echo $(branchNameToTileCase) # outputs secondValue
            displayName: Second variable pass