trigger:
- '*'

variables:
- template: pipeline/vars.yaml

steps:
- template: pipeline/print-vars.yaml
- script: echo "##vso[task.setvariable variable=appName]Application2"
- template: pipeline/print-vars.yaml
