trigger:
- '*'

variables:
- template: pipeline/vars.yaml

steps:
- script: echo App name is ${{ variables.appName }}.
- script: echo App name is $(variables.appName).
- script: echo "##vso[task.setvariable variable=appName]Application2"
- script: echo App name is ${{ variables.appName }}.
- script: echo App name is $(variables.appName).
